"""ASI-06: Memory and Context Manipulation — Provenance Tracker.

Tracks the origin (provenance) of every data item stored in an agent's
memory or context, and verifies the chain of custody before that data is
used in a sensitive operation.

Threat model
------------
* An adversary injects crafted content into a document, web page, or tool
  response that the agent stores in its persistent memory or working context.
* On a subsequent task, the agent retrieves the poisoned memory item and
  uses it as if it were authoritative internal knowledge.
* Without provenance tracking, there is no way to distinguish internally-
  generated knowledge from untrusted external content.

Defense strategy
----------------
* Each item written to agent memory is tagged with a ``ProvenanceRecord``
  capturing the data source, trust level, timestamp, and a short content
  fingerprint.
* ``verify_chain()`` reconstructs the full custody chain for an item and
  checks that every record in the chain meets the minimum required trust
  level for the intended operation.
* Items derived from untrusted sources are flagged so downstream consumers
  can apply additional scrutiny.
"""
from __future__ import annotations

import hashlib
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Trust levels
# ---------------------------------------------------------------------------


class SourceTrustLevel(IntEnum):
    """Ordinal trust level for a data source.

    Levels align conceptually with the broader threat model:

    * ``INTERNAL``: data generated by the agent itself or its operators.
    * ``VERIFIED``: data from a source that has been cryptographically or
      structurally verified (e.g., a signed API response).
    * ``EXTERNAL``: data from an unauthenticated external source (web,
      email, uploaded document).
    * ``UNTRUSTED``: data explicitly marked as untrusted or adversarial.
    """

    UNTRUSTED = 0
    EXTERNAL = 1
    VERIFIED = 2
    INTERNAL = 3


# ---------------------------------------------------------------------------
# Provenance record
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ProvenanceRecord:
    """Immutable record describing the origin of a single memory item.

    Attributes
    ----------
    item_id:
        UUID of the memory item this record belongs to.
    record_id:
        UUID uniquely identifying this provenance record.
    source:
        Human-readable description of the data source (e.g. a URL, tool
        name, or ``"agent_internal"``).
    trust_level:
        Trust level assigned to this source.
    content_hash:
        SHA-256 hex digest of the content at the time of recording.
        Used to detect later tampering.
    recorded_at:
        UTC timestamp when the record was created.
    parent_record_id:
        UUID of the preceding provenance record in the chain, or ``None``
        for the initial record.
    notes:
        Optional free-text annotation (e.g. transformation applied).
    """

    item_id: str
    record_id: str
    source: str
    trust_level: SourceTrustLevel
    content_hash: str
    recorded_at: datetime
    parent_record_id: str | None = None
    notes: str = ""


# ---------------------------------------------------------------------------
# Chain verification result
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ChainVerificationResult:
    """Result of a ``ProvenanceTracker.verify_chain()`` call.

    Attributes
    ----------
    valid:
        ``True`` when the chain is intact and all records meet the required
        trust level.
    item_id:
        The memory item whose chain was verified.
    chain_length:
        Number of provenance records in the chain.
    minimum_trust:
        The minimum ``SourceTrustLevel`` observed across all chain records.
    required_trust:
        The trust level threshold requested by the caller.
    violations:
        Human-readable descriptions of any chain violations found.
    """

    valid: bool
    item_id: str
    chain_length: int
    minimum_trust: SourceTrustLevel
    required_trust: SourceTrustLevel
    violations: list[str]


# ---------------------------------------------------------------------------
# Tracker
# ---------------------------------------------------------------------------


class ProvenanceTracker:
    """Records and verifies data provenance for agent memory items.

    The tracker is an in-memory store.  For persistent provenance, callers
    should serialise and persist records externally.

    Example
    -------
    >>> tracker = ProvenanceTracker()
    >>> item_id = tracker.record(
    ...     content=b"summary of quarterly earnings",
    ...     source="https://example.com/earnings.pdf",
    ...     trust_level=SourceTrustLevel.EXTERNAL,
    ... )
    >>> result = tracker.verify_chain(item_id, SourceTrustLevel.INTERNAL)
    >>> result.valid
    False  # EXTERNAL < INTERNAL
    """

    def __init__(self) -> None:
        # item_id -> ordered list of ProvenanceRecord (oldest first)
        self._chains: dict[str, list[ProvenanceRecord]] = {}

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def record(
        self,
        content: bytes | str,
        source: str,
        trust_level: SourceTrustLevel,
        item_id: str | None = None,
        notes: str = "",
    ) -> str:
        """Record provenance for a new or updated memory item.

        Parameters
        ----------
        content:
            The content being stored.  A SHA-256 hash is computed and
            stored; the original content is **not** retained by the tracker.
        source:
            Description of the data origin.
        trust_level:
            Trust level of the source.
        item_id:
            If provided, appends a new provenance record to an existing
            item's chain (e.g., after a transformation).  If ``None``, a
            new item is created.
        notes:
            Optional annotation for this record (e.g., transformation name).

        Returns
        -------
        str
            The ``item_id`` of the recorded item (useful when a new item
            is created and the caller didn't supply an ``item_id``).
        """
        if item_id is None:
            item_id = str(uuid.uuid4())

        raw = content if isinstance(content, bytes) else content.encode("utf-8")
        content_hash = hashlib.sha256(raw).hexdigest()

        parent_id: str | None = None
        if item_id in self._chains and self._chains[item_id]:
            parent_id = self._chains[item_id][-1].record_id

        record = ProvenanceRecord(
            item_id=item_id,
            record_id=str(uuid.uuid4()),
            source=source,
            trust_level=trust_level,
            content_hash=content_hash,
            recorded_at=datetime.now(tz=timezone.utc),
            parent_record_id=parent_id,
            notes=notes,
        )

        if item_id not in self._chains:
            self._chains[item_id] = []
        self._chains[item_id].append(record)

        logger.debug(
            "Recorded provenance item_id=%r source=%r trust=%s",
            item_id,
            source,
            trust_level.name,
        )
        return item_id

    def get_chain(self, item_id: str) -> list[ProvenanceRecord]:
        """Return the full provenance chain for *item_id*.

        Parameters
        ----------
        item_id:
            The memory item to look up.

        Returns
        -------
        list[ProvenanceRecord]
            Ordered oldest-first.  Empty list if item is not known.
        """
        return list(self._chains.get(item_id, []))

    def verify_chain(
        self,
        item_id: str,
        required_trust: SourceTrustLevel,
        expected_content_hash: str | None = None,
    ) -> ChainVerificationResult:
        """Verify the chain of custody for *item_id*.

        The chain is considered valid when:

        1. At least one record exists for *item_id*.
        2. Every record in the chain has a ``trust_level`` >=
           *required_trust*.
        3. Optionally, the most recent record's ``content_hash`` matches
           *expected_content_hash* (tamper detection).

        Parameters
        ----------
        item_id:
            The memory item to verify.
        required_trust:
            Minimum trust level every chain link must meet.
        expected_content_hash:
            If provided, the hash of the most recent record must match.
            This detects external modification of the stored content.

        Returns
        -------
        ChainVerificationResult
        """
        chain = self._chains.get(item_id, [])
        violations: list[str] = []

        if not chain:
            return ChainVerificationResult(
                valid=False,
                item_id=item_id,
                chain_length=0,
                minimum_trust=SourceTrustLevel.UNTRUSTED,
                required_trust=required_trust,
                violations=[
                    f"No provenance records found for item_id={item_id!r}. "
                    "The item may not have been recorded or the id is incorrect."
                ],
            )

        # Find minimum trust across the chain.
        min_trust = min(record.trust_level for record in chain)

        if min_trust < required_trust:
            violations.append(
                f"Chain minimum trust {min_trust.name} is below required "
                f"{required_trust.name}.  One or more records originate from "
                "a source whose trust level is insufficient for this operation."
            )

        # Verify parent linkage is internally consistent.
        for i, record in enumerate(chain):
            if i == 0:
                if record.parent_record_id is not None:
                    violations.append(
                        f"First chain record has a non-None parent_record_id "
                        f"({record.parent_record_id!r}); expected None."
                    )
            else:
                expected_parent = chain[i - 1].record_id
                if record.parent_record_id != expected_parent:
                    violations.append(
                        f"Chain link broken at record index {i}: "
                        f"parent_record_id {record.parent_record_id!r} does not "
                        f"match preceding record_id {expected_parent!r}."
                    )

        # Optional content hash check on the latest record.
        if expected_content_hash is not None:
            actual_hash = chain[-1].content_hash
            if actual_hash != expected_content_hash:
                violations.append(
                    f"Content hash mismatch on latest record: "
                    f"expected {expected_content_hash[:16]}... "
                    f"actual {actual_hash[:16]}... "
                    "The stored content may have been tampered with."
                )

        return ChainVerificationResult(
            valid=len(violations) == 0,
            item_id=item_id,
            chain_length=len(chain),
            minimum_trust=min_trust,
            required_trust=required_trust,
            violations=violations,
        )

    def forget(self, item_id: str) -> None:
        """Remove all provenance records for *item_id*.

        Parameters
        ----------
        item_id:
            Memory item to forget.
        """
        self._chains.pop(item_id, None)

    def known_items(self) -> list[str]:
        """Return all known item IDs.

        Returns
        -------
        list[str]
        """
        return list(self._chains)
